language: node_js
node_js:
- 8.11.4
script:
- npm run lint
- npm run test:coverage && cat test-coverage/lcov.info | node_modules/.bin/coveralls
- npm run build
deploy:
  skip_cleanup: true
  provider: npm
  email: dev@noblockno.party
  api_key:
    secure: PmNlWcuW2uPztdpyjS2s6P5IeCNAovRqoIXFwzw1BZF66rsyi5QeQyzzcHJwfg/8VLRVg8Bmwy+cS4NyIxZgcOQYebMeRXTsdxdgXDTH6ZuB549/pikZvPQeqQV9YO6rhR4Ue0cvPnocH1Ol/cSE+JdU1c9opDfy5rb7AS3jdl8eKHoA6B2R8Q7KHuyRgw3N6eK6RJIMkjR0hojrnxGRCAvhtWXMvvjAwot+qWj71bKeOU35LmrOV3JM3RBaVsYAqJ18HQsKOVVXAogN7ehjR1f1aIxZo+HLLHVGrE/DRv+/7KILeOqmkVYKmjYglpUjs1Nk0MQCV/IGUoP8VkdnZaqPMXlzDHiyCbk/ypUzHSJkOs5AnoyvwtsnmL06idtdfGlIeF5HENLTczXqK5LWTZumxH27NccSAJKO9hW9lxT6pmpXi+eHpMWnY0cuKCTBIfyFyy/AXxGemhxIT/KDt1GA6oEJyJ4iqOmlMFTzGagA2uFfRsBmal1yaS5Tc4rnwjBOMCGfT2Z5N6XZddLZIMQg0Z3SshUQKpZpE6woL7hg63QKnVCQQmh92JSmLDxhLyCtFkptXvo/FuvriNc0uy5IgEG+1jD/+Lc1CSqOpxZFtXeX5B0xkaA1WZAv/wKZ/8ogkQSnAczQUQt/n1sJdAXJ33aC7UP2Lilysjj1NOQ=
  on:
    tags: true
    repo: noblocknoparty/validation
